apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: ifilyaninitmo/itdt-contained-frontend:master
          ports:
          - containerPort: 3000
          env:
          - name: REACT_APP_USERNAME
            valueFrom:
              configMapKeyRef:
                name: frontend-config
                key: REACT_APP_USERNAME
          - name: REACT_APP_COMPANY_NAME
            valueFrom:
              configMapKeyRef:
                name: frontend-config
                key: REACT_APP_COMPANY_NAME